catalog/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.index, name='index'),
    path('blogs/', views.BlogListView.as_view(), name='blog_list'),
    path('blogs/<int:pk>', views.BlogDetailView.as_view(), name='blog_detail'),
    path('bloggers/', views.BloggerListView.as_view(), name='blogger_list'),
    path('bloggers/<int:pk>', views.BloggerDetailView.as_view(), name='blogger_detail'),
    path('blogs/<int:pk>/create', views.CommentCreate.as_view(), name='comment_create'),
    path('blogger/createblogger', views.BloggerCreate.as_view(), name='blogger_create'),
    path('blogger/<int:pk>/updateblogger', views.BloggerUpdate.as_view(), name='blogger_update'),
    path('blogger/<int:pk>/deleteblogger', views.BloggerDelete.as_view(), name='blogger_delete'),
    path('blog/createblog', views.BlogCreate.as_view(), name='blog_create'),
    path('blog/<int:pk>/updateblog', views.BlogUpdate.as_view(), name='blog_update'),
    path('blog/<int:pk>/deleteblog', views.BlogDelete.as_view(), name='blog_delete')
    
    
]

miniblog/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', include('catalog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

catalog/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=200)
    blogger = models.ForeignKey('Blogger', on_delete=models.RESTRICT, null=True)

    content = models.TextField(max_length=2000, help_text='Enter content of the blog')
    post_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse("blog_detail", args=[str(self.id)])
    class Meta:
        ordering = ['-post_date']
        permissions = [("can_mark_returned", "Set blog as returned")]

class Blogger(models.Model):
    name = models.CharField(max_length=20)
    bio = models.TextField(max_length=1000, help_text='Enter a brief biography of the blogger')

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse("blogger_detail", args=[str(self.id)])
from django.contrib.auth.models import User
class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField(verbose_name='Description')
    created_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_date']
    
    
    

catalog/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']  # Chỉ định các trường bạn muốn hiển thị trên form

catalog/views.py
from django.shortcuts import render
from .models import Blog, Blogger, Comment
from django.views import generic
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from django.shortcuts import get_object_or_404
from .forms import CommentForm
from django.http import HttpResponseRedirect
# Create your views here.
def index(request):
    num_blogs = Blog.objects.all().count()
    num_bloggers = Blogger.objects.all().count()
    context = {
        'num_blogs' : num_blogs,
        'num_bloggers': num_bloggers
    }
    
    return render(request, 'index.html', context=context)

class BlogListView(generic.ListView):
    model = Blog
    paginate_by = 5
class BlogDetailView(generic.DetailView):
    model = Blog
class BloggerListView(generic.ListView):
    model = Blogger
class BloggerDetailView(generic.DetailView):
    model = Blogger


# @permission_required("catalog.can_mark_returned")
class CommentCreate(CreateView):
    model = Comment
    form_class = CommentForm
    template_name = 'comment_form.html'

    def form_valid(self, form):
        form.instance.blog = get_object_or_404(Blog, pk=self.kwargs['pk'])
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('blog_detail', kwargs={'pk': self.object.blog.pk})
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['blog'] = get_object_or_404(Blog, pk=self.kwargs['pk'])
        return context


class BloggerCreate(PermissionRequiredMixin, CreateView):
    model = Blogger
    fields = '__all__'
    permission_required = 'catalog.add_blogger'

class BloggerUpdate(PermissionRequiredMixin, UpdateView):
    model = Blogger
    # Not recommended (potential security issue if more fields added)
    fields = '__all__'
    permission_required = 'catalog.change_blogger'

class BloggerDelete(PermissionRequiredMixin, DeleteView):
    model = Blogger
    success_url = reverse_lazy('blogger_list')
    permission_required = 'catalog.delete_blogger'
        
class BlogCreate(PermissionRequiredMixin, CreateView):
    model = Blog
    fields = '__all__'
    permission_required = 'catalog.add_blog'

class BlogUpdate(PermissionRequiredMixin, UpdateView):
    model = Blog
    # Not recommended (potential security issue if more fields added)
    fields = '__all__'
    permission_required = 'catalog.change_blog'

class BlogDelete(PermissionRequiredMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy('blog_list')
    permission_required = 'catalog.delete_blog'

    

catalog/templates/base_generic.html
<html lang="en">
  <head>
    {% block title %}
      <title>Mini Blog</title>
    {% endblock %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
  </head>
  <body>
    <div class="container-fluid">
        <div class="row">
          <div class="col-sm-2">
            {% block sidebar %}
              <ul class="sidebar-nav">
                <li><a href="{% url 'index' %}">Home</a></li>
                <li><a href="{% url 'blog_list' %}">All blogs</a></li>
                <li><a href="{% url 'blogger_list'%}">All blogger</a></li>
                {% if user.is_authenticated %}
                    <li>User: {{ user.get_username }}</li>
                    <li>
                    <form id="logout-form" method="post" action="{% url 'logout' %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-link">Logout</button>
                    </form>
                    </li>
                {% else %}
                    <li><a href="{% url 'login' %}?next={{ request.path }}">Login</a></li>
                {% endif %}
              </ul>
            {% endblock %}
          </div>
          <div class="col-sm-10">{% block content %}{% endblock %}
            {% block pagination %}
    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
  {% endblock %}
  <figure class="figureimg">
    <img src="https://cdn.marvel.com/content/1x/doctorstrange_01-1920x1080_copy.jpg" srcset="https://cdn.marvel.com/content/1x/doctorstrange_01-1920x1080_copy.jpg"
    alt="Doctor Strange" class="image" loading="lazy">
  </figure>
          </div>
        </div>
      </div>
  </body>
</html>

catalog/templates/catalog/blog_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Blog: {{ blog }}</h1>

{% if blog.blog_set.all %}

<p>You can't delete this author until all their books have been deleted:</p>
<ul>
  {% for blog in blog.blog_set.all %}
    <li><a href="{% url 'blog_detail' blog.pk %}">{{blog}}</a></li>
  {% endfor %}
</ul>

{% else %}
<p>Are you sure you want to delete the blogger?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete.">
</form>
{% endif %}

{% endblock %}

catalog/templates/catalog/blog_detail.html
{% extends 'base_generic.html' %}
{% block content %}
<h1>{{blog.title}}</h1>
<p><strong>Post date: </strong>{{blog.post_date}}</p>
<p><strong>Blogger: </strong>{{blog.blogger}}</p>
<p><strong>Description: </strong>
    <br />
    {{blog.content}}</p>
<div style='margin-left:0px;margin-top:20px; background-color: white'>
    <h4>Comments</h4>
    <hr />
  {% if user.is_authenticated %}
    {% for comment in blog.comments.all %}
    <p><strong>{{comment.user.username}}-</strong>({{comment.created_date|date:"Y-m-d H:i"}}) - {{comment.text}}</p>
    {% endfor%}
    <p><a href="{% url 'comment_create' pk=blog.pk %}" style="color: #104164"><strong>Create comment</strong></a></p>
  {% else %}
    <p><a href="{% url "login" %}">Login</a> to view and comment</p>
  {% endif%}
</div>
{% endblock %}

{% block sidebar %}
  {{ block.super }}

  {% if perms.catalog.change_blog or perms.catalog.delete_blog %}
  <hr>
  <ul class="sidebar-nav">
    {% if perms.catalog.change_blog %}
      <li><a href="{% url 'blog_update' blog.id %}">Update blog</a></li>
    {% endif %}
    {% if perms.catalog.delete_blog %}
      <li><a href="{% url 'blog_delete' pk=blog.id %}">Delete blog</a></li>
    {% endif %}
    </ul>
  {% endif %}
{% endblock %}

catalog/templates/catalog/blog_form.html
{% extends "base_generic.html" %}

{% block content %}
<form action="" method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit" />
</form>
{% endblock %}

catalog/templates/catalog/blog_list.html
{% extends 'base_generic.html' %}
{% block content %}
<h1>All Blogs</h1>
{% if blog_list %}
<ul>
    {% for blog in blog_list%}
    <li><a href="{{ blog.get_absolute_url }}">{{ blog.title }}</a>({{ blog.post_date }})__{{ blog.blogger.name}}</li>
    {% endfor %}
</ul>
{% else %}
<p>There are no blog in my blog's home</p>
{% endif %}
{% if perms.catalog.add_blog %}
   <p><a href="{% url 'blog_create' %}" style="color: #104164"><strong>Create blog</strong></a></p>
{% endif %}
{% endblock %}

catalog/templates/catalog/blogger_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Blogger: {{ blogger }}</h1>

{% if blogger.blog_set.all %}

<p>You can't delete this author until all their books have been deleted:</p>
<ul>
  {% for blog in blogger.blog_set.all %}
    <li><a href="{% url 'blog_detail' blog.pk %}">{{blog}}</a></li>
  {% endfor %}
</ul>

{% else %}
<p>Are you sure you want to delete the blogger?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete.">
</form>
{% endif %}

{% endblock %}

catalog/templates/catalog/blogger_detail.html
{% extends 'base_generic.html' %}
{% block content %}
<h1>Blogger: {{blogger.name}}</h1>
<h5>Bio</h5>
<p>{{ blogger.bio}}</p>
<h5>Blogs list</h5>
<ul>
{% for blog in blogger.blog_set.all%}
    <li><a href="{{blog.get_absolute_url}}">{{blog.title}}</a>({{blog.post_date}})</li>
{% endfor %}
</ul>
{% endblock%}

{% block sidebar %}
  {{ block.super }}

  {% if perms.catalog.change_blogger or perms.catalog.delete_blogger %}
  <hr>
  <ul class="sidebar-nav">
    {% if perms.catalog.change_blogger %}
      <li><a href="{% url 'blogger_update' blogger.id %}">Update blogger</a></li>
    {% endif %}
    {% if not blogger.blog_set.all and perms.catalog.delete_blogger %}
      <li><a href="{% url 'blogger_delete' blogger.id %}">Delete blogger</a></li>
    {% endif %}
    </ul>
  {% endif %}

{% endblock %}

catalog/templates/catalog/blogger_form.html
{% extends "base_generic.html" %}

{% block content %}
<form action="" method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit" />
</form>
{% endblock %}

catalog/templates/catalog/blogger_list.html
{% extends 'base_generic.html' %}
{% block content %}
<h1>All Bloggers</h1>
{% if blogger_list %}
<ul>
    {% for blogger in blogger_list%}
    <li><a href="{{blogger.get_absolute_url}}">{{ blogger.name }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>There are no bloggers</p>
{% endif %}
{% if perms.catalog.add_blogger %}
   <p><a href="{% url 'blogger_create' %}" style="color:#104164"><strong>Create blogger</strong></a></p>
{% endif %}
{% endblock%}

catalog/templates/index.html
{% extends "base_generic.html" %}
{% block content %}
<h1>Your Blogs Home</h1>
<p>Welcome to MyBlog, a website develop by <strong>VyVyAn</strong>!</p>
    
<p>We have collected many usefull blog for you</p>
<h3>The blog has the following record count:</h3>
<ul>
    <li><strong>Blogs: </strong>{{ num_blogs }}</li>
    <li><strong>Bloggers: </strong>{{ num_bloggers }}</li>
</ul>
{% endblock %}

templates/comment_form.html
{% extends "base_generic.html" %}

{% block content %}
<form action="" method="post">
  {% csrf_token %}
  <p>Post your comment for: <a href="{{blog.get_absolute_url}}">{{blog.title}}</a></p>
  <table>
    {{ form.as_table }}
  </table>
  <p>Enter comment about blog here</p>
  <input type="submit" value="Submit" />
</form>
{% endblock %}